### ISSUE TITLE
TypeScript examples

### ISSUE THREAD

**Issue by richytong** [a-synchronous/rubico#1]
rubico is compatible with TypeScript, right now there's not enough examples. All examples should go in the `examples` directory. All examples should be runnable, with output that makes sense.

Here is one I did: [squaredOdds.ts](https://github.com/a-synchronous/rubico/blob/master/examples/squaredOdds.ts)

I plan to document the examples in the near future.

Of course, more JavaScript examples are always welcome.

Also, please include any relevant links (if any) in the example source.

**Comment by toltarisa** [comment]
hey @richytong, i wanna help on ts examples.I checked your squaredOdds example and CONTRIBUTING.md file , how should i start ?Can you assign me a basic example to start with ?
Thanks

**Comment by richytong** [comment]
@toltarisa Welcome! Actually I'm going to revamp the example system so it's more useful. [Here's](https://github.com/a-synchronous/rubico/issues/41) the new issue for examples (`/x/`)

**Comment by richytong** [comment]
I've decided against TypeScript examples because I fundamentally do not support that direction. If you're still down to help with JavaScript examples, the issue is open

**Comment by richytong** [comment]
this is why https://youtu.be/jmPZztKIFf4?t=108

**Comment by richytong** [comment]
You know what, I don't know why I was so mean. Also the examples are very necessary. I would love help on this, I just need to set up some tooling.
