### ISSUE TITLE
How are the builds done right now?

### ISSUE THREAD

**Issue by getify** [a-synchronous/rubico#163]
Tried to figure out how you build the `index.js` and `es.js` files, but couldn't figure that out. Are you using rollup or some other tool? Or are you manually building them?

**Comment by richytong** [comment]
Hello! The builds are a WIP at the moment. Before, there was no build process - everything was in `index.js`. I realized the need to split everything up recently so I split out the declarations in `index.js` of v1.5.19 into `_internal/`. This is all gearing up for the next minor, v1.6.

Regarding what's happening with the builds, I was planning on using the declarations in `_internal/` to generate various exports in a new `/dist/` folder. This folder would have a structure resembling something like this:

```
/dist/rubico.js - contains the core API (the 24 functions). Assigns to `globalThis` or whatever global is available the global variable `rubico`
/dist/rubico.min.js - contains just the core API minified. Same global shenanigans as the above.
/dist/rubico.es.js - contains an ES Modules version of the core API
/dist/rubico.es.min.js - contains a minified ES Modules version of just the core API
/dist/pipe.js - contains just the `pipe` function of the core API. Assigns the global variable `pipe`.
/dist/pipe.min.js - minified version of above
/dist/pipe.es.js - ES Modules version of above
/dist/fork.js - ...
...rest of core API methods
/dist/x/defaultsDeep.js - contains just the `defaultsDeep` function of `rubico/x`. `rubico/x/` is a place for basically everything else that could be in rubico.
/dist/x/defaultsDeep.min.js
/dist/x/defaultsDeep.es.js
/dist/x/defaultsDeep.es.min.js
...rest of rubico/x/ methods
```

I just took a look at rollup - seems to be exactly what I need! I'll have to dig into it a bit more though.

**Comment by getify** [comment]
Rollup is certainly a very popular tool, but I am not sure whether it will be right for your project or not. Worth looking into.

Part of why I asked is because I've written a tool [Moduloze](https://github.com/getify/moduloze) which is similar to Rollup but is more geared for library authors than Rollup seems to be (which seems to be more app-oriented). Moduloze lets you author cross-environment modules (like those in your lib) in CJS format, and then it can convert those to UMD (for browser) and ES-Modules (for browser and Node 14+) formats.

There's two ideal use-cases for a tool like that: library authors (I wrote it because I wanted that capability for my own various OSS libraries) and one-time codemod upgrades of old code bases to modern ESM style.

I was curious if you'd like help in exploring getting something like Moduloze up and going?

**Comment by richytong** [comment]
Moduloze looks very interesting. It seems to actually do what I'm right about to do, or at least handles a significant chunk of it for me. I would be happy to incorporate it into rubico's build process.

**Comment by getify** [comment]
That's cool to hear. I'd be quite happy to help do that!

One thing I noticed when looking at your code is that you currently distribute a single "es.js" file, which from what I can tell is a careful concatenation of all the contents of the individual modules into a single combined ES module. This is an interesting and much less common way of distributing ES modules. There are definitely legitimate reasons to want to do so, but most don't. I was curious if there's a particular set of objectives/constraints guiding how you want to distribute?

Typically, a library would distribute each part as a separate ES module file, and then optionally also distribute an "index.mjs" file that "rolls up" (imports) all the modules and then re-exports them. For example:

```js
export * from "./some/modules/a.mjs";
export * from "./some/modules/b.mjs";
import C from "./some/modules/c.mjs";
export { C as Whatever };
..
```

That way someone could then do:

```html
<script type="module" src="/path/to/rubico/dist/index.mjs"></script>
```

Or like in Node:

```js
import * as Rubico from "/path/to/rubico/dist/index.mjs";
```

This is what Moduloze currently supports for ES Module export: it basically can generate the "index.mjs" for you if you don't already have one crafted. The UMD format has a more natural transformation for single-all-in-one-file bundling (wrapping an IIFE around everything), so Moduloze also supports that. But not yet for ESM format.

----

However, seeing your single combined ES module file got me to thinking about whether that's a useful optional mode for Moduloze to support. There's some tricky caveats to handle (mostly around name collisions), which your code may not struggle with but in general it could make a feature like that more complicated.

But in any case, I've [created this issue](https://github.com/getify/moduloze/issues/11) to document and track my thinking/research/progress around that. It can certainly motivate that work if there's a strong reason you would want to take advantage of it for Rubico. ;-)

**Comment by richytong** [comment]
Regarding distribution, the best case I can think of is to allow everyone to import exactly what functions they need based on a single url. I was thinking to let people specify the functions as filepaths in any order - something like the following:

```
https://unpkg.com/rubico@1.6.0/dist/pipe/map/filter/index.js - assigns global `pipe`, `map`, `filter`
https://unpkg.com/rubico@1.6.0/dist/pipe/map/filter/es.js - `export { pipe, map, filter }; export default { pipe, map, filter }`
https://unpkg.com/rubico@1.6.0/dist/map/filter/pipe/index.js - file would be exactly the same as above index
https://unpkg.com/rubico@1.6.0/dist/map/filter/pipe/es.js - file would be exactly the same as above es.js
https://unpkg.com/rubico@1.6.0/dist/pipe/map/filter/defaultsDeep - also could include rubico/x/ functions
```

This would require a bunch of codegen with functions specific to each combination. I haven't tested this, it's a crazy idea, but maybe crazy enough to work, at least for the majority who probably use some stable number of functions I'm guessing. 

Apart from that, some must haves:
```
/dist/rubico.js - cjs export of only core 24 functions
/dist/rubico.es.js - esm export of only core 24 functions
/dist/pipe.js - cjs only pipe
/dist/pipe.es.js - esm pipe
... other core exports
/dist/defaultsDeep.js - I'm thinking actually we don't need the `/x/` for `dist`
/dist/defaultsDeep.es.js
... other /x/ exports
```

Regarding the issue, it does look like something I could do. I think I see what you're saying, I'll dive into that issue now.
