### ISSUE TITLE
function ideas

### ISSUE THREAD

**Issue by richytong** [a-synchronous/rubico#184]
```
flatMap.series
flatMap.pool
transform.parallel
transform.pool
transform.while
reduce.parallel
reduce.pool
reduce.while
pipe.chain
```

Your suggestions are welcome!

**Comment by phhu** [comment]
`unfold` would be nice. (see https://stackoverflow.com/questions/71605121/implementation-of-async-unfold-function-in-javascript / https://stackoverflow.com/questions/49542944/loop-until-with-ramda )

**Comment by lulldev** [comment]
@richytong yo!
after fp-ts in rubico i dont fully understand alternation in pipe.

in fp-ts we can generalize computation by Either monad. for example:

```ts
pipe(
  E.right(1),
  E.map((val) => console.log(val)), // log 1
  E.mapLeft(() => console.log('left value'), // not achievable in this case
)
```
and this is good way for handling errors and ellegant break computation, but its about special data structure.

in rubico i have when/unless/switchCase and raw structure without error signs (tags). and my code without either structure start expand with additional logic.

@richytong what you think about controlling flow in rubico and either monad in fp? maybe you can highlight solutions for this cases. thanks!

**Comment by richytong** [comment]
@kalagin Either monad is not a replacement for alternation, it is only a replacement for error handling with imperative try/catch syntax. rubico's `tryCatch` is the function equivalent to the pure functional programming Either monad. With `tryCatch` you can still throw an error and have it be caught in an error handler, which is similar to calling E.left on an Either monad and then calling E.match to handle the error.

To your example:
```js
// rubico
tryCatch(1, val => 1, () => 'err value')

// fp-ts
pipe(
  E.right(1),
  E.map((val) => 1), // output: 1
  E.mapLeft(() => 'err value')), // not achievable in this case
)
```

A toy http handler with tryCatch

```js
const myHandler = (request, response) => tryCatch(request, pipe([
  request => parseRequestBody(request),
  data => myDb.get(data.userId),
  user => {
    response.end(JSON.stringify(user))
  },
]), error => {
  console.error(error)
  response.end(error.message)
})
```
