### ISSUE TITLE
How do we deal with short-circuit in pipelines using Rubico?

### ISSUE THREAD

**Issue by thelinuxlich** [a-synchronous/rubico#191]

**Comment by richytong** [comment]
You could throw errors in pipelines wrapped with tryCatch to shortcircuit.

```javascript
tryCatch(pipe([
  doSomething,
  doSomethingElse,
  function shortCircuitByThrowing() {
    if (someTrueCondition) {
      throw new Error('I will effectively shortcircuit this pipeline')
    }
  },
  someFuncThatIsNotReachedBecauseOfShortCircuiting,
]), error => {
  console.log('caught error:', error.message) // caught error: I will effectively shortcircuit this pipeline
})
```

**Comment by thelinuxlich** [comment]
the intention wasn't to throw errors, but to keep going like Railway Oriented Programming: https://fsharpforfunandprofit.com/rop/ 

I see libraries like Sanctuary doing that transparently using Maybe

**Comment by richytong** [comment]
If you'd like to use the Maybe monad, it is possible with rubico, you would just need to explicitly use flatMap on the monadic value

```javascript
pipe([
  Maybe,
  flatMap(myFunc),
  flatMap(myOtherFunc),
])(myValue)
```

and a quick Maybe monad implementation
```javascript
function Maybe(value) {
  return {
    flatMap(func) { // chain works here as well
      return Maybe(value == null ? value : func(value))
    },
  }
}
```

maybe we could think about a special version of pipe to make this syntax look less clunky? Maybe pipe.chain

**Comment by thelinuxlich** [comment]
I think this is a good example from the Sanctuary introductory video: https://youtu.be/a2astdDbOjk?t=1157

**Comment by thelinuxlich** [comment]
But I agree pipe.chain might be the right direction
