### ISSUE TITLE
map doesn't return a Array if the result of the ArrayMapper is a Promise

### ISSUE THREAD

**Issue by thelinuxlich** [a-synchronous/rubico#196]
```
map((_) => Promise.resolve(_))(['foo','bar'])

// returns Promise instead of [Promise, Promise]
```

**Comment by richytong** [comment]
This is expected behavior. When anything returned by the mapper is a promise the end result is a Promise that should resolve an array of synchronous (not promise) values.

```javascript
map((_) => Promise.resolve(_))(['foo','bar']).then(console.log) // ['foo', 'bar']
```

**Comment by thelinuxlich** [comment]
That's very counterintuitive, shouldn't map preserve the type of the collection provided?

**Comment by richytong** [comment]
For this lib besides primitive types the only other type that is not really considered a “collection” is the Promise. The unique thing about this lib is every function resolves any promises by default, so yes it is counterintuitive if you consider a Promise to be a collection. However if you think about Promises only as things to be resolved for their values the behavior should make more sense. The end result of this decision is code with less promise cruft so you can focus on the part of your code that actually matters

**Comment by thelinuxlich** [comment]
Per functional standards, map operates on a functor and returns the same functor type, right? I'm not passing a Promise to map, I'm passing a array of primitives.

**Comment by richytong** [comment]
The paradigm is not exactly functional, it's [a]synchronous functional for this very reason. rubico does not entirely conform to functional standards regarding Promises for the sake of practicality

**Comment by thelinuxlich** [comment]
Hmm I don't understand why you can't follow the standards by returning [Promise, Promise], that creates incompatibility in case someone mixes Rubico with other functional libraries. At least you should state these exceptions in the docs

**Comment by richytong** [comment]
Okay, I’ll try to make it a point to state these in the docs

**Comment by richytong** [comment]
I don't see how it would create incompatibilities. At worst there's the mental overhead of remember that rubico functions have this property.

**Comment by thelinuxlich** [comment]
well, for starters it's not fantasy-land compatible, you have a `map` function that seems to be `Functor f => (a -> b) -> f a -> f b` but it actually behaves like `Functor f => (a -> Promise) -> f a -> Promise b`

**Comment by richytong** [comment]
It should be fantasy-land compatible if we just leave promises out of it. For synchronous values map behaves normally

**Comment by richytong** [comment]
Actually even with promises it should be fantasy-land compatible. rubico supports some of the algebraic datatypes defined in fantasyland. fantasy-land doesn't even formalize promises
