### ISSUE TITLE
Have you thought about implementing Rubico(or an alternative version) fully as unary functions?

### ISSUE THREAD

**Issue by thelinuxlich** [a-synchronous/rubico#198]
When all functions return only one output and receive only one input(unary functions), the code acquires the elegant features of lambda calculus. It's a much simpler abstraction, less cognitive load, easier to do tacit/point-free programming style.

**Comment by richytong** [comment]
I think you can just curry reduce 

const curriedReduce = curry.arity(2, reduce)

const add = (a, b) => a + b

curriedReduce(add)(0)([1, 2, 3, 4, 5]) // 10
