### ISSUE TITLE
migrate all normal tests to thunk-test

### ISSUE THREAD

**Issue by richytong** [a-synchronous/rubico#209]
this way we can share them in dist test and not have to duplicate

**Comment by lulldev** [comment]
maybe split big file with tests like tests in "x" folder?
i think it look like simplest for support.

**Comment by lulldev** [comment]
i can get it, but need more info

**Comment by richytong** [comment]
@kalagin This issue is no longer relevant, I'm thinking right now about a more standard way of testing, while still deduplicating the tests. Closing this in favor of https://github.com/a-synchronous/rubico/issues/230
