### ISSUE TITLE
rubico v2

### ISSUE THREAD

**Issue by richytong** [a-synchronous/rubico#231]
- [x] Refactor all transducer functionality into Transducer.js from `pipe`, `map`, `filter`, and `flatMap`
 - [x] Remove GeneratorFunction and AsyncGeneratorFunction functionality in `map`, `filter`, `flatMap`, and `reduce`
 - [x] Refactor reducer chaining functionality into AggregateReducer.js from `reduce`
 - [x] Remove Duplex stream handling from `flatMap`
 - [x] Remove binary handling from `flatMap`
 - [x] Promises as arguments for all core functions
 - [x] Eager API for all core functions
 - [x] Automate benchmarks
 - [x] Remove the .sync property functions
 - [x] Remove the .withIndex property functions
 - [x] Deprecate map.own
 - [x] `fork` renamed to `all`
 - [x] `all` renamed to `every`
 - [x] `any` renamed to `some`
 - [x] new `dist-test` only validates syntax with `require`
 - [x] migrate `forEach` into core API.
 - [x] refactor transducer functionality from `forEach` into `Transducer.forEach`
 - [x] async performance improvements
 - [x] `_internal/arrayExtend` stops treating strings like arrays so `transform` creates arrays of strings as expected

**Comment by kalagin** [comment]
maybe we can add releases in github and changelogs?

**Comment by richytong** [comment]
@kalagin that sounds like a great idea, I'll have to see about how to add the releases on github

**Comment by kalagin** [comment]
1. manual mode, i think you can use something like this https://github.com/github-changelog-generator/github-changelog-generator, and then https://github.com/github-changelog-generator/github-changelog-generator#practical-use-cases
2. github actions, probably we can move npm publish to github actions to and trigger in CI this jobs: 
- https://github.com/marketplace/actions/release-changelog-builder
- https://github.com/marketplace/actions/changelog-from-conventional-commits

**Comment by richytong** [comment]
`gren` doesn't work with our project setup. I'll have to look into this later.
