### ISSUE TITLE
ESM + CommonJS single code source

### ISSUE THREAD

**Issue by richytong** [a-synchronous/rubico#5]
Right now the implementation is duplicated between `index.js` and `rubico.js`. This was my monkeypatch to support both CommonJS and ESM. I need help to remove this duplicate and still support both types of exports.

My current thoughts on this are to look towards babel. There is also the [esm](https://www.npmjs.com/package/esm) module on `npm`, but I want to stay dependency-free. I am willing to add to dev-dependencies, however. I am not sure if esm would just be a dev depedency as I haven't looked into it that far.

**Comment by KonradLinkowski** [comment]
Is this still an issue?

**Comment by richytong** [comment]
I'm resolving this issue currently, will be the next step after the _internal refactor https://github.com/a-synchronous/rubico/issues/153

**Comment by richytong** [comment]
This is done with https://github.com/a-synchronous/rubico/commit/28128c58f243c351415e4b6d18c7c37b71f79262
