### ISSUE TITLE
eq.deep

### ISSUE THREAD

**Issue by richytong** [a-synchronous/rubico#65]
right now `eq` is a strict equality check. `eq.deep` would be a deep strict equality check

```javascript
eq.deep(identity, { a: 1, b: 2, c: 3 })({ a: 1, b: 2, c: 3 }) // true
```

**Comment by KonradLinkowski** [comment]
Is using an npm module a respected solution?

**Comment by richytong** [comment]
I'd like to stick to being dependency free.. for now. I would prefer having an own implementation to iterate on.

**Comment by richytong** [comment]
duplicate of https://github.com/a-synchronous/rubico/issues/207
